
## Funzzy events file
# more details see: https://github.com/cristianoliveira/funzzy
#
# list here all the events and the commands that it should execute

- name: Plugin build
  run: 'mvn install'
  change: ['src/**', 'pom.xml']

- name: Copy build
  run: 'sshpass -p "carlos1305" scp target/BackpackPlugin-1.0-SNAPSHOT.jar carandev@192.168.100.78:Downloads/minecraft-server/plugins/'
  change: 'target/BackpackPlugin-1.0-SNAPSHOT.jar'
